file_categories_personal_list = [{		
	"Name" : "Trash",
	"Content" : ["png", "bat", "jpg", "msg", ".lnk", "html", "pptx", 'ico', 'txt', "oft", "docx", "doc", "zip",".7z", "PNG", "emz", "pst", ".eml", "rar", "swf", "ics"],
        "isCode" : False,
        },
	{"Name":"Installs",
	"Content" : ["exe", "rdp", ],
         "isCode" : False,
	},
	{"Name" : "Data",
	"Content" : ["csv", "xlsx", "xlsm", "xls", "json", "xml", "evtx"],
         "isCode" : False,
	},
	{"Name" : "Documents",
	"Content" : ["pdf", "ppsx"],
         "isCode" : False,
	},
	{"Name" : "Diagrams",
	"Content" : ["vsdx"],
	 "isCode" : False
	},
	{"Name" : "Python Packages",
	"Content" : ["whl"],
         "isCode" : True,
	},
	{"Name" : "Scripts",
	"Content" : [".py", "pac"],
         "isCode" : True,
	},
	{"Name" : "Videos",
	"Content" : [".mp4"],
         "isCode" : False,
	}]

file_categories_personal_dict = {		
	"Trash" : ["png", "bat", "jpg", "msg", ".lnk", "html", "pptx", 'ico', 'txt', "oft", "docx", "doc", "zip",".7z", "PNG", "emz", "pst", ".eml", "rar", "swf", "ics"],
	"Installs" : ["exe", "rdp", "msi"],
	"Diagrams" : ["vsdx"],
	"Data" : ["csv", "xlsx", "xlsm", "xls", "json", "xml", "evtx"],
	"Documents" : ["pdf", "ppsx"],
	"Python Packages" : ["whl", "tar.gz"],
	"CodeBase\Scripts" : [".py", "pac"],
	"Videos" : [".mp4"],
	}
